//! Kademlia discovery wire types (generated by prost + tonic, re-exported for `comm`).
//!
//! Mirrors `comm/src/main/protobuf/coop/rchain/comm/protocol/kademlia.proto` (package
//! `coop.rchain.comm.discovery`).

pub use crate::proto::discovery::*;
